// <auto-generated />
using BimBot.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BimBot.Migrations
{
    [DbContext(typeof(SRO_VT_BIMBOT))]
    [Migration("20230913111237_2023_09_13_2")]
    partial class _2023_09_13_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BimBot.Database.SRO_VT_BIMBOT.BlackListWords", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID")
                        .HasName("PK_dbo._BlackListWords_ID");

                    b.ToTable("_BlackListWords", (string)null);
                });

            modelBuilder.Entity("BimBot.Database.SRO_VT_BIMBOT.Help", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("OptionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_dbo._Help_ID");

                    b.ToTable("_Help", (string)null);
                });

            modelBuilder.Entity("BimBot.Database.SRO_VT_BIMBOT.HelpEmbed", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EmbedDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbedTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Help_ID")
                        .HasColumnType("int");

                    b.Property<bool>("MentionUser")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowThumbnail")
                        .HasColumnType("bit");

                    b.HasKey("ID")
                        .HasName("PK_dbo._HelpEmbed");

                    b.HasIndex("Help_ID");

                    b.ToTable("_HelpEmbed", (string)null);
                });

            modelBuilder.Entity("BimBot.Database.SRO_VT_BIMBOT.HelpMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Help_ID")
                        .HasColumnType("int");

                    b.Property<bool>("MentionUser")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_dbo._HelpMessage");

                    b.HasIndex("Help_ID");

                    b.ToTable("_HelpMessage", (string)null);
                });

            modelBuilder.Entity("BimBot.Database.SRO_VT_BIMBOT.HelpEmbed", b =>
                {
                    b.HasOne("BimBot.Database.SRO_VT_BIMBOT.Help", "Help")
                        .WithMany("HelpEmbeds")
                        .HasForeignKey("Help_ID")
                        .IsRequired()
                        .HasConstraintName("FK_dbo._Help._HelpEmbeds_ID");

                    b.Navigation("Help");
                });

            modelBuilder.Entity("BimBot.Database.SRO_VT_BIMBOT.HelpMessage", b =>
                {
                    b.HasOne("BimBot.Database.SRO_VT_BIMBOT.Help", "Help")
                        .WithMany("HelpMessages")
                        .HasForeignKey("Help_ID")
                        .IsRequired()
                        .HasConstraintName("FK_dbo._Help._HelpMessages_ID");

                    b.Navigation("Help");
                });

            modelBuilder.Entity("BimBot.Database.SRO_VT_BIMBOT.Help", b =>
                {
                    b.Navigation("HelpEmbeds");

                    b.Navigation("HelpMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
